name: Branch Naming Convention

on:
  create:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ ! $BRANCH_NAME =~ ^(feature\/[A-Za-z0-9]+-[A-Za-z0-9-]+)$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention: feature/TICKET_ID-short-description"
            exit 1
          fi
